### ISSUE TITLE
Own night takes own rook [getValidMoves returns invalid move]

### ISSUE THREAD

**Issue by coolusaHD** [cogsys-tuebingen/ai_competition#5]
## Description
I run my agent and suddenly I saw this:
![image](https://user-images.githubusercontent.com/56646413/148966287-c56593ff-35e1-4b62-9ed2-3cd8a39b525d.png)

On the right bottom corner was my rook and now my own knight is there. That alone is defently not a valid move.
Furthermore you can see the last position of my knight as red dot. So there is also an unvalid move from there as knight.

Maybe there are some bugs in the Castle Right moves...

You can test that behavior with that code:

## Code
```
        gs = GameState()

        gs.board = ['bR', 'bB', 'bK', 'bN', '--', 'bR',
                    'bp', 'bp', '--', '--', '--', 'bp',
                    '--', '--', '--', 'bp', '--', 'wp',
                    '--', '--', '--', '--', '--', '--',
                    'bB', 'wp', 'wp', 'wp', '--', '--',
                    'wR', 'wB', 'wK', 'wN', '--', 'wR']

        gs.whiteToMove = True

        moves = gs.getValidMoves()
```

**Comment by toddChavezz** [comment]
Indeed, I could reproduce this and couldn't anymore, after I set all castling rights to false. But how did you reach this position? is it possible that you have an incorrect initial position of the board in your code? Normally the initial king positions are one square further to the right. And then, when you land in a position like this, the kings already lost their castling rights and this bug cannot happen.
I will still fix this as it is obviously not correct, thank you for pointing this out.

**Comment by coolusaHD** [comment]
I think i the new `ChessEngine.py` version the flip the board is not commented out.

**Comment by coolusaHD** [comment]
Also the test board is not commented out!

**Comment by toddChavezz** [comment]
yes you are right, thanks a lot. in that case, the initial error of this issue should not happen.

**Comment by coolusaHD** [comment]
Thats great.

It would be also great if you can notice me when you fixed the bug here in this issue :)

**Comment by toddChavezz** [comment]
I will notify you in this thread :) however, this doesn't seem like a priority at the moment as I think it doesn't occur when the position is set up correctly
