### ISSUE TITLE
Get KeyError on undoMove()

### ISSUE THREAD

**Issue by coolusaHD** [cogsys-tuebingen/ai_competition#7]
## Description

it dont happen very often but when it happen I cannot found any problem in my code.
I'm using undo move like this in my code
```
gs.makeMove(move)
score = RekursiveFunktion(x,y)
gs.undoMove()
```

## Error Output

```
Process Process-6:
Traceback (most recent call last):
  File "C:\Projekte\chess_ai\ChessEngine.py", line 177, in undoMove
    self.game_log[tuple(self.board)] -= 1
KeyError: ('--', 'bR', 'bN', 'bK', 'bB', 'bR', '--', 'bp', 'bp', '--', 'bp', 'bp', '--', 'bB', '--', 'bp', '--', '--', '--', '--', '--', 'wp', 'wp', 'wp', 'wp', 'wp', 'wp', '--', '--', 'wR', 'wR', 'wB', 'wN', 'wK', '--', 'wR')
```

**Comment by toddChavezz** [comment]
does your recursive function also operate on the GameState object? do you have a board position and corresponding move that is undone for which this happens? My AI basically operates the same way and I didn't encounter this so far.

**Comment by coolusaHD** [comment]
I think my mobility function which operates on the same gamestate was the problem.
